const d = (
  generic,
  brand,
  drugClass,
  indication,
  sideEffect,
  schedule = "None",
  pearl,
  mnemonic,
) => ({
  id: generic.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  generic,
  brand,
  drugClass,
  indication,
  sideEffect,
  schedule,
  pearl,
  mnemonic,
});

export const TOP_200_DRUGS = [
  d("lisinopril", "Zestril", "ACE inhibitor", "hypertension, heart failure", "dry cough, hyperkalemia", "None", "Avoid in pregnancy; monitor potassium.", "ACE inhibitors usually end in -pril."),
  d("losartan", "Cozaar", "ARB", "hypertension, diabetic kidney protection", "dizziness, hyperkalemia", "None", "Common fallback when an ACE inhibitor causes cough.", "ARBs usually end in -sartan."),
  d("valsartan", "Diovan", "ARB", "hypertension, heart failure", "dizziness, hyperkalemia", "None", "Check for duplicate ARB therapy.", "Think sartan = angiotensin receptor blocker."),
  d("amlodipine", "Norvasc", "dihydropyridine calcium channel blocker", "hypertension, angina", "edema, flushing", "None", "Ankle swelling is a classic exam clue.", "Many DHP calcium channel blockers end in -dipine."),
  d("nifedipine ER", "Procardia XL", "dihydropyridine calcium channel blocker", "hypertension, angina", "edema, headache", "None", "Extended-release form should not be crushed.", "-dipine points to a blood-pressure lowering calcium channel blocker."),
  d("diltiazem ER", "Cardizem CD", "non-dihydropyridine calcium channel blocker", "rate control, angina, hypertension", "bradycardia, constipation", "None", "Watch for pulse-lowering duplication with beta blockers.", "Diltiazem and verapamil slow the heart."),
  d("verapamil ER", "Calan SR", "non-dihydropyridine calcium channel blocker", "rate control, angina", "constipation, bradycardia", "None", "Constipation is especially common.", "Verapamil is the constipation-prone calcium channel blocker."),
  d("metoprolol succinate", "Toprol XL", "beta blocker", "hypertension, heart failure, rate control", "bradycardia, fatigue", "None", "Succinate is extended release; tartrate is immediate release.", "Beta blockers often end in -olol."),
  d("carvedilol", "Coreg", "beta blocker", "heart failure, hypertension", "dizziness, bradycardia", "None", "Used often in heart failure because of alpha and beta effects.", "-olol = beta blocker."),
  d("propranolol", "Inderal", "beta blocker", "tremor, migraine prevention, hypertension", "bradycardia, fatigue", "None", "Nonselective beta blocker; can worsen asthma.", "Propranolol is the classic tremor and migraine beta blocker."),
  d("hydrochlorothiazide", "Microzide", "thiazide diuretic", "hypertension, edema", "hypokalemia, photosensitivity", "None", "Often paired with ACE inhibitors or ARBs.", "Think thiazide = potassium can go down."),
  d("chlorthalidone", "Thalitone", "thiazide-like diuretic", "hypertension", "hypokalemia, dizziness", "None", "Longer acting than hydrochlorothiazide.", "Chlorthalidone is the long-acting thiazide-like option."),
  d("furosemide", "Lasix", "loop diuretic", "edema, heart failure", "hypokalemia, dehydration", "None", "Loops pull off fluid fast; monitor electrolytes.", "Loops like furosemide are strong fluid removers."),
  d("spironolactone", "Aldactone", "potassium-sparing diuretic", "heart failure, edema, resistant hypertension", "hyperkalemia, gynecomastia", "None", "Potassium goes up, not down.", "Spironolactone spares potassium."),
  d("torsemide", "Demadex", "loop diuretic", "edema, heart failure", "hypokalemia, dehydration", "None", "Another loop that may appear in heart-failure questions.", "Torsemide works like furosemide."),
  d("clonidine", "Catapres", "alpha-2 agonist", "hypertension, ADHD adjunct", "sedation, dry mouth", "None", "Abrupt withdrawal can trigger rebound hypertension.", "Clonidine can calm blood pressure but stopping suddenly is risky."),
  d("hydralazine", "Apresoline", "vasodilator", "hypertension", "headache, reflex tachycardia", "None", "Common add-on in harder-to-control blood pressure regimens.", "Hydralazine directly relaxes vessels."),
  d("nitroglycerin SL", "Nitrostat", "nitrate", "acute angina", "headache, hypotension", "None", "Store in the original tightly closed container.", "Nitro = chest pain relief under the tongue."),
  d("isosorbide mononitrate", "Imdur", "nitrate", "angina prevention", "headache, hypotension", "None", "Used for prevention, not immediate relief.", "Mononitrate maintains nitrate coverage."),
  d("digoxin", "Lanoxin", "cardiac glycoside", "heart failure, atrial fibrillation", "nausea, visual halos", "None", "Toxicity questions love nausea plus yellow/green vision changes.", "Digoxin toxicity = GI upset and visual halos."),
  d("amiodarone", "Cordarone", "antiarrhythmic", "rhythm control", "thyroid changes, pulmonary toxicity", "None", "High-yield counseling point: many organ toxicities.", "Amiodarone touches almost every organ system."),
  d("sotalol", "Betapace", "antiarrhythmic", "rhythm control", "bradycardia, QT prolongation", "None", "Watch QT-prolongation combinations.", "Sotalol slows rhythm and can stretch QT."),
  d("atorvastatin", "Lipitor", "statin", "hyperlipidemia", "myalgias, elevated liver enzymes", "None", "Avoid in pregnancy; report unexplained muscle pain.", "Statins end in -statin and lower LDL."),
  d("rosuvastatin", "Crestor", "statin", "hyperlipidemia", "myalgias, elevated liver enzymes", "None", "Potent LDL lowering in a small tablet.", "Rosuvastatin is a strong statin."),
  d("simvastatin", "Zocor", "statin", "hyperlipidemia", "myalgias, elevated liver enzymes", "None", "More interaction-prone than some other statins.", "Simvastatin is a classic evening statin."),
  d("pravastatin", "Pravachol", "statin", "hyperlipidemia", "myalgias", "None", "Often remembered as one of the less interaction-heavy statins.", "Still a -statin, still LDL lowering."),
  d("ezetimibe", "Zetia", "cholesterol absorption inhibitor", "hyperlipidemia", "diarrhea, fatigue", "None", "Often added when a statin alone is not enough.", "Ezetimibe blocks cholesterol absorption."),
  d("fenofibrate", "Tricor", "fibrate", "high triglycerides", "gallstones, muscle effects", "None", "Triglyceride-focused therapy.", "Fibrates fit triglyceride problems."),
  d("aspirin", "Bayer Aspirin", "antiplatelet NSAID", "pain, cardiovascular prevention", "GI bleed, bruising", "None", "Often held before procedures because of bleeding risk.", "Aspirin thins platelets."),
  d("clopidogrel", "Plavix", "antiplatelet", "post-stent and cardiovascular protection", "bleeding, bruising", "None", "A common second antiplatelet after stent placement.", "Clopidogrel helps prevent platelet clumping."),
  d("warfarin", "Jantoven", "vitamin K antagonist", "anticoagulation", "bleeding", "None", "INR monitoring is a frequent exam clue.", "Warfarin = bleeding risk plus INR."),
  d("apixaban", "Eliquis", "DOAC", "anticoagulation", "bleeding", "None", "No routine INR monitoring, but bleeding still matters.", "Apixaban is a common oral factor Xa inhibitor."),
  d("rivaroxaban", "Xarelto", "DOAC", "anticoagulation", "bleeding", "None", "Another factor Xa inhibitor.", "Rivaroxaban is oral anticoagulation without INR checks."),
  d("dabigatran", "Pradaxa", "direct thrombin inhibitor", "anticoagulation", "bleeding, dyspepsia", "None", "Swallow capsules whole; moisture-sensitive packaging matters.", "Dabigatran capsules should stay in their original container."),
  d("enoxaparin", "Lovenox", "low-molecular-weight heparin", "anticoagulation", "bleeding, injection-site bruising", "None", "Subcutaneous injectable anticoagulant.", "Enoxaparin = abdominal injections and bruising."),
  d("metformin", "Glucophage", "biguanide", "type 2 diabetes", "diarrhea, nausea", "None", "Take with food if GI upset is a problem.", "Metformin is the standard first-line type 2 diabetes drug."),
  d("insulin glargine", "Lantus", "long-acting insulin", "diabetes", "hypoglycemia", "None", "Do not mix with other insulins in the same syringe.", "Glargine gives a flat basal insulin effect."),
  d("insulin lispro", "Humalog", "rapid-acting insulin", "diabetes", "hypoglycemia", "None", "Used around meals for quick coverage.", "Lispro is the quick meal insulin."),
  d("insulin aspart", "NovoLog", "rapid-acting insulin", "diabetes", "hypoglycemia", "None", "Another rapid mealtime insulin.", "Aspart acts fast around meals."),
  d("semaglutide", "Ozempic", "GLP-1 receptor agonist", "type 2 diabetes, weight loss", "nausea, vomiting", "None", "Stored refrigerated before first use; slowed gastric emptying is high yield.", "GLP-1 agents often cause nausea and help weight loss."),
  d("dulaglutide", "Trulicity", "GLP-1 receptor agonist", "type 2 diabetes", "nausea, vomiting", "None", "Weekly injectable device.", "Dulaglutide is a weekly GLP-1 option."),
  d("empagliflozin", "Jardiance", "SGLT2 inhibitor", "type 2 diabetes, heart failure", "genital yeast infection, dehydration", "None", "Watch for urinary and genital infection counseling points.", "SGLT2 drugs often end in -gliflozin."),
  d("dapagliflozin", "Farxiga", "SGLT2 inhibitor", "type 2 diabetes, heart failure", "genital yeast infection, dehydration", "None", "Another gliflozin with cardiorenal benefit.", "-gliflozin = urine glucose loss."),
  d("glipizide", "Glucotrol", "sulfonylurea", "type 2 diabetes", "hypoglycemia, weight gain", "None", "More hypoglycemia risk than metformin.", "Sulfonylureas squeeze out insulin."),
  d("glimepiride", "Amaryl", "sulfonylurea", "type 2 diabetes", "hypoglycemia, weight gain", "None", "Another hypoglycemia-prone oral diabetes agent.", "Sulfonylurea = think low sugar risk."),
  d("pioglitazone", "Actos", "thiazolidinedione", "type 2 diabetes", "edema, weight gain", "None", "Fluid retention is a recurring test clue.", "Pioglitazone can puff patients up."),
  d("sitagliptin", "Januvia", "DPP-4 inhibitor", "type 2 diabetes", "nasopharyngitis, pancreatitis warning", "None", "Ends in -gliptin.", "-gliptin drugs raise incretin activity."),
  d("levothyroxine", "Synthroid", "thyroid hormone", "hypothyroidism", "palpitations if over-replaced", "None", "Take on an empty stomach consistently.", "Levothyroxine replaces low thyroid hormone."),
  d("methimazole", "Tapazole", "antithyroid", "hyperthyroidism", "rash, agranulocytosis warning", "None", "Opposite direction from levothyroxine.", "Methimazole slows thyroid production."),
  d("prednisone", "Deltasone", "oral corticosteroid", "inflammation, asthma flare", "hyperglycemia, insomnia", "None", "Take with food; taper when appropriate.", "Prednisone is the common oral steroid."),
  d("methylprednisolone", "Medrol Dosepak", "oral corticosteroid", "inflammation", "hyperglycemia, insomnia", "None", "Dose packs are common outpatient tapers.", "Medrol Dosepak = steroid taper."),
  d("sertraline", "Zoloft", "SSRI", "depression, anxiety", "GI upset, sexual dysfunction", "None", "One of the most common first-line antidepressants.", "SSRIs boost serotonin."),
  d("fluoxetine", "Prozac", "SSRI", "depression, anxiety", "insomnia, GI upset", "None", "Long half-life is a classic detail.", "Fluoxetine sticks around longer."),
  d("escitalopram", "Lexapro", "SSRI", "depression, anxiety", "nausea, sexual dysfunction", "None", "A common anxiety starter medication.", "Escitalopram is a common SSRI starter."),
  d("citalopram", "Celexa", "SSRI", "depression", "QT prolongation, nausea", "None", "Higher doses raise QT concerns.", "Citalopram is the SSRI with memorable QT caution."),
  d("paroxetine", "Paxil", "SSRI", "depression, anxiety", "sedation, sexual dysfunction", "None", "Often remembered for anticholinergic feel and withdrawal issues.", "Paroxetine can be more sedating."),
  d("venlafaxine ER", "Effexor XR", "SNRI", "depression, anxiety", "nausea, elevated blood pressure", "None", "Think serotonin and norepinephrine.", "SNRIs hit serotonin plus norepinephrine."),
  d("duloxetine", "Cymbalta", "SNRI", "depression, neuropathic pain", "nausea, sweating", "None", "Shows up in pain and mood questions.", "Duloxetine covers mood and nerve pain."),
  d("bupropion XL", "Wellbutrin XL", "NDRI", "depression, smoking cessation support", "insomnia, seizure risk", "None", "Often chosen when sexual side effects are a concern.", "Bupropion is stimulating and seizure-sensitive."),
  d("trazodone", "Desyrel", "serotonin modulator", "depression, insomnia off-label", "sedation, dizziness", "None", "Low-dose insomnia use is common.", "Trazodone often means sleepy."),
  d("amitriptyline", "Elavil", "tricyclic antidepressant", "depression, neuropathic pain, migraine prevention", "sedation, anticholinergic effects", "None", "TCA questions often feature dry mouth and drowsiness.", "Amitriptyline is the sleepy dry-mouth TCA."),
  d("buspirone", "BuSpar", "anxiolytic", "generalized anxiety", "dizziness, headache", "None", "Not for immediate panic relief.", "Buspirone is the scheduled daily anxiety drug, not a rescue sedative."),
  d("aripiprazole", "Abilify", "atypical antipsychotic", "schizophrenia, bipolar disorder, depression adjunct", "akathisia, weight changes", "None", "Used often as an add-on to antidepressants.", "Aripiprazole is the add-on atypical you see often."),
  d("quetiapine", "Seroquel", "atypical antipsychotic", "schizophrenia, bipolar disorder", "sedation, weight gain", "None", "Sedation is a recurring clue.", "Quetiapine tends to be sedating."),
  d("olanzapine", "Zyprexa", "atypical antipsychotic", "schizophrenia, bipolar disorder", "weight gain, metabolic effects", "None", "High-yield atypical for metabolic changes.", "Olanzapine = weight gain clue."),
  d("risperidone", "Risperdal", "atypical antipsychotic", "schizophrenia, bipolar disorder", "prolactin increase, EPS", "None", "Watch for movement disorder questions.", "Risperidone can raise prolactin."),
  d("haloperidol", "Haldol", "typical antipsychotic", "psychosis, agitation", "EPS, QT prolongation", "None", "Classic high-EPS antipsychotic.", "Haloperidol = older antipsychotic with movement side effects."),
  d("lithium", "Lithobid", "mood stabilizer", "bipolar disorder", "tremor, toxicity risk", "None", "Narrow therapeutic index; dehydration can worsen toxicity.", "Lithium needs careful level monitoring."),
  d("lamotrigine", "Lamictal", "antiepileptic mood stabilizer", "bipolar disorder, seizures", "rash", "None", "Slow titration helps reduce serious rash risk.", "Lamotrigine = think rash warning."),
  d("alprazolam", "Xanax", "benzodiazepine", "anxiety, panic disorder", "sedation, dependence", "CIV", "Controlled substance with misuse potential.", "Benzos calm fast but carry dependence risk."),
  d("lorazepam", "Ativan", "benzodiazepine", "anxiety, agitation", "sedation, dependence", "CIV", "Common inpatient and acute-anxiety choice.", "Lorazepam is a go-to short-term benzo."),
  d("clonazepam", "Klonopin", "benzodiazepine", "panic disorder, seizures", "sedation, dependence", "CIV", "Longer acting benzo.", "Clonazepam lasts longer than alprazolam."),
  d("diazepam", "Valium", "benzodiazepine", "anxiety, muscle spasm", "sedation, dependence", "CIV", "Another long half-life benzo.", "Diazepam is the classic long-acting benzo."),
  d("zolpidem", "Ambien", "sedative-hypnotic", "insomnia", "drowsiness, complex sleep behaviors", "CIV", "Take right before bedtime.", "Zolpidem is a sleep medicine with next-day impairment risk."),
  d("gabapentin", "Neurontin", "antiepileptic / neuropathic pain agent", "neuropathic pain, seizures", "dizziness, drowsiness", "None", "Often used for nerve pain.", "Gabapentin is a common nerve-pain helper."),
  d("pregabalin", "Lyrica", "antiepileptic / neuropathic pain agent", "neuropathic pain, fibromyalgia", "dizziness, edema", "CV", "Pregabalin is federally controlled.", "Pregabalin is like gabapentin but schedule V."),
  d("levetiracetam", "Keppra", "antiepileptic", "seizures", "somnolence, irritability", "None", "Behavior changes can show up in counseling questions.", "Keppra is common and can make mood edgy."),
  d("phenytoin", "Dilantin", "antiepileptic", "seizures", "gingival hyperplasia, ataxia", "None", "Narrow therapeutic clues and gum overgrowth appear on exams.", "Phenytoin = gums and gait problems."),
  d("carbamazepine", "Tegretol", "antiepileptic", "seizures, trigeminal neuralgia", "dizziness, blood dyscrasias", "None", "Interaction-heavy antiepileptic.", "Carbamazepine can interact and suppress counts."),
  d("divalproex sodium", "Depakote", "antiepileptic / mood stabilizer", "seizures, bipolar disorder, migraine prevention", "tremor, hepatotoxicity", "None", "Also seen as valproic acid on exams.", "Depakote can affect the liver."),
  d("topiramate", "Topamax", "antiepileptic", "seizures, migraine prevention", "cognitive slowing, weight loss", "None", "Patients often remember word-finding issues.", "Topiramate can make thinking feel slower."),
  d("sumatriptan", "Imitrex", "triptan", "migraine abortive", "tingling, chest pressure", "None", "Used to stop a migraine, not prevent it.", "Triptans terminate migraines."),
  d("donepezil", "Aricept", "acetylcholinesterase inhibitor", "Alzheimer disease", "nausea, diarrhea", "None", "Common dementia medication.", "Donepezil helps symptoms of Alzheimer disease."),
  d("memantine", "Namenda", "NMDA receptor antagonist", "Alzheimer disease", "dizziness, headache", "None", "Another dementia therapy often paired with donepezil.", "Memantine is another Alzheimer medication."),
  d("ropinirole", "Requip", "dopamine agonist", "Parkinson disease, restless legs syndrome", "nausea, somnolence", "None", "Dopamine agonist class clue.", "Ropinirole replaces dopamine signaling."),
  d("pramipexole", "Mirapex", "dopamine agonist", "Parkinson disease, restless legs syndrome", "nausea, somnolence", "None", "Another restless-legs and Parkinson option.", "Pramipexole is a dopamine agonist."),
  d("acetaminophen", "Tylenol", "analgesic", "pain, fever", "hepatotoxicity in overdose", "None", "Common combination product ingredient.", "Acetaminophen hides inside many combo products."),
  d("ibuprofen", "Advil", "NSAID", "pain, fever", "GI upset, kidney effects", "None", "Food may reduce stomach upset.", "Ibuprofen is the common OTC NSAID."),
  d("naproxen", "Aleve", "NSAID", "pain, inflammation", "GI upset, kidney effects", "None", "Longer acting OTC NSAID.", "Naproxen lasts longer than ibuprofen."),
  d("meloxicam", "Mobic", "NSAID", "arthritis pain", "GI upset, edema", "None", "Usually once daily.", "Meloxicam is a daily NSAID."),
  d("celecoxib", "Celebrex", "COX-2 selective NSAID", "arthritis pain", "edema, cardiovascular warning", "None", "Celecoxib is the COX-2 exam favorite.", "Celecoxib is the selective NSAID."),
  d("tramadol", "Ultram", "opioid agonist", "moderate pain", "dizziness, sedation", "CIV", "Serotonergic and seizure caution may be tested.", "Tramadol is controlled and can affect serotonin."),
  d("hydrocodone/acetaminophen", "Norco", "opioid combination", "pain", "constipation, sedation", "CII", "Combination opioid with acetaminophen.", "Hydrocodone combos are schedule II."),
  d("oxycodone/acetaminophen", "Percocet", "opioid combination", "pain", "constipation, sedation", "CII", "Another acetaminophen-containing opioid combo.", "Percocet = oxycodone plus acetaminophen."),
  d("morphine sulfate", "MS Contin", "opioid analgesic", "severe pain", "constipation, respiratory depression", "CII", "High-alert medication in the inpatient setting.", "Morphine is a classic schedule II opioid."),
  d("hydromorphone", "Dilaudid", "opioid analgesic", "severe pain", "constipation, respiratory depression", "CII", "Potent opioid and high-alert medication.", "Hydromorphone is strong and easy to overdose if confused."),
  d("naloxone", "Narcan", "opioid antagonist", "opioid overdose reversal", "withdrawal symptoms", "None", "Used to reverse opioid-induced respiratory depression.", "Naloxone knocks opioids off receptors."),
  d("cyclobenzaprine", "Flexeril", "muscle relaxant", "muscle spasm", "drowsiness, dry mouth", "None", "Sedation is common.", "Cyclobenzaprine relaxes muscles and makes patients sleepy."),
  d("buprenorphine/naloxone", "Suboxone", "partial opioid agonist combination", "opioid use disorder", "constipation, headache", "CIII", "Used for maintenance treatment in opioid use disorder.", "Suboxone supports opioid recovery."),
  d("albuterol HFA", "Ventolin HFA", "short-acting beta agonist", "acute bronchospasm", "tremor, tachycardia", "None", "Rescue inhaler, not a controller.", "Albuterol opens lungs fast."),
  d("fluticasone/salmeterol", "Advair Diskus", "ICS/LABA inhaler", "asthma, COPD maintenance", "thrush, hoarseness", "None", "Rinse mouth after inhaled corticosteroid use.", "Controller inhaler, not rescue."),
  d("budesonide/formoterol", "Symbicort", "ICS/LABA inhaler", "asthma, COPD maintenance", "thrush, hoarseness", "None", "Maintenance inhaler with steroid plus long-acting bronchodilator.", "Symbicort controls, it does not rescue."),
  d("tiotropium", "Spiriva", "long-acting muscarinic antagonist", "COPD, asthma maintenance", "dry mouth", "None", "Maintenance bronchodilator, not rescue.", "Tiotropium keeps airways open over time."),
  d("ipratropium/albuterol", "DuoNeb", "SAMA/SABA inhalation solution", "bronchospasm", "dry mouth, tremor", "None", "Common nebulized combo.", "DuoNeb combines two bronchodilators."),
  d("montelukast", "Singulair", "leukotriene receptor antagonist", "allergic rhinitis, asthma maintenance", "headache, neuropsychiatric warning", "None", "Used for maintenance, not rescue.", "Montelukast blocks leukotrienes."),
  d("fluticasone nasal", "Flonase", "intranasal corticosteroid", "allergic rhinitis", "nosebleeds, irritation", "None", "A common daily allergy controller.", "Fluticasone nose spray calms allergies."),
  d("cetirizine", "Zyrtec", "antihistamine", "allergies", "drowsiness", "None", "Less sedating than diphenhydramine but still can cause drowsiness.", "Cetirizine is a daily antihistamine."),
  d("loratadine", "Claritin", "antihistamine", "allergies", "headache, dry mouth", "None", "Common non-drowsy allergy choice.", "Loratadine is the less-sedating allergy tablet."),
  d("fexofenadine", "Allegra", "antihistamine", "allergies", "headache", "None", "Another non-drowsy allergy option.", "Fexofenadine fights allergies with less sedation."),
  d("diphenhydramine", "Benadryl", "first-generation antihistamine", "allergies, itching", "sedation, anticholinergic effects", "None", "Sedating and drying; common OTC clue.", "Diphenhydramine is the sleepy antihistamine."),
  d("benzonatate", "Tessalon Perles", "antitussive", "cough", "drowsiness, numb mouth if chewed", "None", "Capsules must be swallowed whole.", "Do not chew benzonatate."),
  d("guaifenesin", "Mucinex", "expectorant", "chest congestion", "nausea", "None", "Helps loosen mucus.", "Guaifenesin gets gunk moving."),
  d("omeprazole", "Prilosec", "PPI", "GERD, ulcer disease", "headache, diarrhea", "None", "PPIs usually end in -prazole.", "Prazole means proton pump inhibitor."),
  d("pantoprazole", "Protonix", "PPI", "GERD, ulcer disease", "headache, diarrhea", "None", "Another common inpatient and outpatient PPI.", "Pantoprazole is another -prazole."),
  d("famotidine", "Pepcid", "H2 blocker", "heartburn, ulcer disease", "headache, dizziness", "None", "Think H2 blocker instead of proton pump inhibitor.", "Famotidine blocks histamine-2 acid signaling."),
  d("ondansetron", "Zofran", "5-HT3 antagonist", "nausea, vomiting", "headache, constipation", "None", "QT prolongation is a classic caution.", "Ondansetron stops nausea."),
  d("promethazine", "Phenergan", "antihistamine antiemetic", "nausea, motion sickness", "sedation, anticholinergic effects", "None", "Sedating antiemetic.", "Promethazine is sleepy nausea relief."),
  d("metoclopramide", "Reglan", "prokinetic antiemetic", "gastroparesis, nausea", "drowsiness, EPS", "None", "Movement disorder warning is high yield.", "Metoclopramide can move the gut and trigger EPS."),
  d("sucralfate", "Carafate", "GI protectant", "ulcer healing", "constipation", "None", "Coats the stomach lining.", "Sucralfate is the ulcer coating drug."),
  d("dicyclomine", "Bentyl", "antispasmodic", "irritable bowel syndrome", "dry mouth, dizziness", "None", "Anticholinergic symptom pattern is common.", "Dicyclomine calms bowel spasms."),
  d("polyethylene glycol 3350", "MiraLAX", "osmotic laxative", "constipation", "bloating", "None", "Powder mixed into liquid.", "PEG pulls water into the stool."),
  d("lactulose", "Generlac", "osmotic laxative", "constipation, hepatic encephalopathy", "gas, diarrhea", "None", "Can appear in liver-related questions.", "Lactulose lowers ammonia and softens stool."),
  d("docusate sodium", "Colace", "stool softener", "constipation prevention", "mild cramping", "None", "Softener, not a strong stimulant laxative.", "Docusate softens; it does not strongly push."),
  d("senna", "Senokot", "stimulant laxative", "constipation", "cramping", "None", "Stimulant bowel mover.", "Senna stimulates the bowel."),
  d("bisacodyl", "Dulcolax", "stimulant laxative", "constipation", "cramping", "None", "Another stimulant laxative.", "Bisacodyl pushes the bowel to move."),
  d("loperamide", "Imodium A-D", "antidiarrheal", "diarrhea", "constipation", "None", "OTC diarrhea treatment.", "Loperamide locks diarrhea down."),
  d("mesalamine", "Lialda", "5-ASA anti-inflammatory", "ulcerative colitis", "headache, abdominal pain", "None", "Shows up in inflammatory bowel disease questions.", "Mesalamine = bowel anti-inflammatory."),
  d("amoxicillin", "Amoxil", "penicillin antibiotic", "bacterial infections", "rash, diarrhea", "None", "Penicillin allergy is a common exam clue.", "Amoxicillin is a basic penicillin."),
  d("amoxicillin/clavulanate", "Augmentin", "penicillin/beta-lactamase inhibitor", "bacterial infections", "diarrhea", "None", "Clavulanate commonly adds stomach upset.", "Augmentin is stronger amoxicillin with clavulanate."),
  d("azithromycin", "Zithromax", "macrolide antibiotic", "bacterial infections", "GI upset, QT prolongation", "None", "The Z-Pak antibiotic.", "Azithromycin is the famous Z-Pak."),
  d("doxycycline", "Vibramycin", "tetracycline antibiotic", "acne, tick-borne disease, infections", "photosensitivity, GI upset", "None", "Take with plenty of water and avoid excess sun.", "Doxycycline = sun sensitivity clue."),
  d("cephalexin", "Keflex", "cephalosporin antibiotic", "skin, urinary infections", "diarrhea, rash", "None", "Common outpatient cephalosporin.", "Cephalexin is a classic cephalosporin."),
  d("cefdinir", "Omnicef", "cephalosporin antibiotic", "respiratory and ear infections", "diarrhea", "None", "Can discolor stool red with iron.", "Cefdinir plus iron can redden stool."),
  d("ceftriaxone", "Rocephin", "cephalosporin antibiotic", "serious bacterial infections", "diarrhea, injection-site pain", "None", "Often given by injection.", "Ceftriaxone is a strong injectable cephalosporin."),
  d("ciprofloxacin", "Cipro", "fluoroquinolone antibiotic", "bacterial infections", "tendon injury, GI upset", "None", "Separate from multivalent cations like iron and calcium.", "Cipro = tendon warning."),
  d("levofloxacin", "Levaquin", "fluoroquinolone antibiotic", "bacterial infections", "tendon injury, QT prolongation", "None", "Another fluoroquinolone with tendon warnings.", "Levofloxacin = tendon warning plus QT."),
  d("sulfamethoxazole/trimethoprim", "Bactrim DS", "sulfonamide antibiotic", "urinary and skin infections", "rash, hyperkalemia", "None", "Often written as TMP-SMX or SMX-TMP.", "Bactrim can raise potassium and trigger sulfa issues."),
  d("nitrofurantoin", "Macrobid", "urinary anti-infective", "urinary tract infection", "nausea", "None", "Used for uncomplicated lower UTI, not pyelonephritis.", "Nitrofurantoin stays in the urine."),
  d("metronidazole", "Flagyl", "nitroimidazole antibiotic", "anaerobic infections, bacterial vaginosis", "metallic taste, nausea", "None", "Avoid alcohol because of a disulfiram-like reaction concern.", "Metronidazole = no alcohol."),
  d("clindamycin", "Cleocin", "lincosamide antibiotic", "skin and anaerobic infections", "diarrhea", "None", "C. diff association is a common exam clue.", "Clindamycin is the diarrhea-heavy antibiotic."),
  d("fluconazole", "Diflucan", "azole antifungal", "fungal infections", "nausea, liver effects", "None", "Common oral yeast treatment.", "Fluconazole treats many yeast infections."),
  d("nystatin", "Mycostatin", "antifungal", "oral candidiasis", "mild irritation", "None", "Often swish and swallow or swish and spit depending on product.", "Nystatin treats thrush."),
  d("valacyclovir", "Valtrex", "antiviral", "herpes infections", "headache, nausea", "None", "Prodrug related to acyclovir.", "Valacyclovir is the easier-dosing herpes antiviral."),
  d("acyclovir", "Zovirax", "antiviral", "herpes infections", "nausea, headache", "None", "Another common herpes antiviral.", "Acyclovir fights herpes viruses."),
  d("oseltamivir", "Tamiflu", "antiviral", "influenza", "nausea, vomiting", "None", "Most helpful when started early.", "Tamiflu is the flu antiviral."),
  d("tamsulosin", "Flomax", "alpha-1 blocker", "benign prostatic hyperplasia", "dizziness, orthostasis", "None", "Often taken after the same meal each day.", "Tamsulosin helps urine flow."),
  d("finasteride", "Proscar", "5-alpha-reductase inhibitor", "benign prostatic hyperplasia", "sexual dysfunction", "None", "Pregnant handlers should avoid crushed tablets.", "Finasteride shrinks the prostate over time."),
  d("oxybutynin ER", "Ditropan XL", "antimuscarinic", "overactive bladder", "dry mouth, constipation", "None", "Anticholinergic symptom pattern again.", "Oxybutynin dries and calms the bladder."),
  d("mirabegron", "Myrbetriq", "beta-3 agonist", "overactive bladder", "increased blood pressure", "None", "Alternative when anticholinergic burden matters.", "Mirabegron relaxes the bladder without being anticholinergic."),
  d("sildenafil", "Viagra", "PDE-5 inhibitor", "erectile dysfunction, pulmonary hypertension", "headache, flushing", "None", "Do not combine with nitrates.", "Sildenafil and nitrates are a dangerous mix."),
  d("norethindrone/ethinyl estradiol", "Loestrin Fe", "combined oral contraceptive", "pregnancy prevention", "nausea, clot risk", "None", "Missed-dose counseling is high yield.", "Combined birth control adds estrogen plus progestin."),
  d("medroxyprogesterone", "Depo-Provera", "progestin", "contraception", "weight changes, irregular bleeding", "None", "Long-acting contraceptive injection.", "Depo is the every-3-month birth control shot."),
  d("estradiol", "Estrace", "estrogen", "menopausal symptoms", "nausea, clot risk", "None", "Hormone therapy question bank favorite.", "Estradiol replaces estrogen."),
  d("triamcinolone cream", "Kenalog", "topical corticosteroid", "eczema, dermatitis", "skin thinning", "None", "Use the thinnest effective layer.", "Topical steroids calm inflamed skin."),
  d("hydrocortisone cream", "Cortizone-10", "topical corticosteroid", "itching, dermatitis", "skin thinning", "None", "Common low-potency OTC steroid.", "Hydrocortisone is the mild topical steroid."),
  d("mupirocin", "Bactroban", "topical antibiotic", "impetigo, localized skin infection", "mild irritation", "None", "Applied to the skin, not an oral antibiotic.", "Mupirocin is a skin antibiotic."),
  d("tretinoin", "Retin-A", "topical retinoid", "acne", "dryness, photosensitivity", "None", "Sun sensitivity appears often.", "Tretinoin speeds skin turnover."),
  d("latanoprost", "Xalatan", "prostaglandin analog", "glaucoma", "eye redness, eyelash growth", "None", "Used once nightly in many glaucoma regimens.", "Latanoprost lowers eye pressure."),
  d("timolol ophthalmic", "Timoptic", "ophthalmic beta blocker", "glaucoma", "eye irritation, bradycardia", "None", "Even eye drops can have systemic beta-blocker effects.", "Timolol eye drops can still slow the heart."),
  d("cyclosporine ophthalmic", "Restasis", "ophthalmic immunomodulator", "dry eye disease", "burning", "None", "Prescription dry-eye therapy.", "Restasis helps chronic dry eye."),
  d("allopurinol", "Zyloprim", "xanthine oxidase inhibitor", "gout prevention", "rash", "None", "Prevents gout; it does not treat an acute flare immediately.", "Allopurinol lowers uric acid."),
  d("colchicine", "Colcrys", "anti-gout agent", "acute gout flare", "diarrhea", "None", "GI upset is a common limit.", "Colchicine can cause diarrhea during gout treatment."),
  d("methotrexate", "Trexall", "DMARD", "rheumatoid arthritis, psoriasis", "mouth sores, liver toxicity", "None", "Usually dosed weekly, not daily.", "Methotrexate weekly is a classic safety point."),
  d("hydroxychloroquine", "Plaquenil", "DMARD", "lupus, rheumatoid arthritis", "retinal toxicity warning", "None", "Eye monitoring matters.", "Hydroxychloroquine can affect the retina."),
  d("adalimumab", "Humira", "TNF inhibitor", "autoimmune disease", "infection risk", "None", "Biologics raise infection concern.", "Humira suppresses immune inflammation."),
  d("potassium chloride", "Klor-Con", "electrolyte supplement", "hypokalemia", "GI irritation", "None", "Do not crush extended-release tablets.", "KCl replaces potassium."),
  d("ferrous sulfate", "Feosol", "iron supplement", "iron deficiency anemia", "constipation, dark stool", "None", "Separate from some antibiotics and levothyroxine.", "Iron turns stools dark and interacts with some meds."),
  d("folic acid", "Folate", "vitamin", "folate deficiency, prenatal support", "rare GI upset", "None", "Often paired with methotrexate regimens.", "Folic acid supports red blood cell production."),
  d("ergocalciferol", "Drisdol", "vitamin D2", "vitamin D deficiency", "rare GI upset", "None", "Often dosed weekly in higher strengths.", "Ergocalciferol is vitamin D2."),
  d("cyanocobalamin", "Vitamin B12", "vitamin", "B12 deficiency", "rare injection-site irritation", "None", "Used orally or by injection depending on deficiency cause.", "Cyanocobalamin is B12 replacement."),
  d("varenicline", "Chantix", "smoking cessation aid", "smoking cessation", "nausea, vivid dreams", "None", "Supports quitting tobacco.", "Varenicline reduces nicotine cravings."),
  d("nicotine patch", "Nicoderm CQ", "nicotine replacement", "smoking cessation", "skin irritation", "None", "Remove the old patch before placing a new one.", "Nicotine patch gives steady nicotine replacement."),
  d("epinephrine auto-injector", "EpiPen", "sympathomimetic", "anaphylaxis", "tachycardia, anxiety", "None", "Inject into the outer thigh for severe allergic reaction.", "Epinephrine is the emergency anaphylaxis medicine."),
  d("meclizine", "Antivert", "antihistamine anti-vertigo agent", "motion sickness, vertigo", "drowsiness", "None", "Sedating anti-vertigo medication.", "Meclizine treats dizziness and can make patients sleepy."),
  d("scopolamine patch", "Transderm Scop", "anticholinergic antiemetic", "motion sickness prevention", "dry mouth, blurred vision", "None", "Patch placed behind the ear.", "Scopolamine patch prevents motion sickness."),
  d("diclofenac gel", "Voltaren Arthritis Pain", "topical NSAID", "localized arthritis pain", "skin irritation", "None", "Topical NSAID avoids some systemic exposure.", "Voltaren gel is NSAID on the skin."),
  d("lidocaine patch", "Lidoderm", "local anesthetic", "localized pain", "skin irritation", "None", "Often used for neuropathic or localized pain.", "Lidocaine patch numbs the area."),
  d("testosterone gel", "AndroGel", "androgen", "low testosterone", "skin irritation, transfer risk", "CIII", "Avoid skin-to-skin transfer to others.", "Testosterone gel can transfer by touch."),
  d("amphetamine/dextroamphetamine", "Adderall", "stimulant", "ADHD", "insomnia, appetite loss", "CII", "Schedule II stimulant; secure storage matters.", "Stimulants raise focus and misuse risk."),
  d("methylphenidate ER", "Concerta", "stimulant", "ADHD", "insomnia, appetite loss", "CII", "Long-acting ADHD stimulant.", "Methylphenidate is a schedule II stimulant."),
  d("lisdexamfetamine", "Vyvanse", "stimulant", "ADHD, binge-eating disorder", "insomnia, appetite loss", "CII", "Prodrug stimulant.", "Vyvanse is a schedule II stimulant prodrug."),
  d("phentermine", "Adipex-P", "sympathomimetic anorexiant", "weight loss short term", "insomnia, increased heart rate", "CIV", "Short-term appetite suppressant.", "Phentermine is a controlled appetite suppressant."),
  d("codeine/acetaminophen", "Tylenol with Codeine", "opioid combination", "pain", "constipation, sedation", "CIII", "Codeine combos are a common schedule III example.", "Codeine plus acetaminophen is not schedule II like oxycodone combos."),
  d("temazepam", "Restoril", "benzodiazepine", "insomnia", "sedation, dependence", "CIV", "Bedtime benzo hypnotic.", "Temazepam is a schedule IV sleep benzo."),
  d("tadalafil", "Cialis", "PDE-5 inhibitor", "erectile dysfunction, BPH", "headache, flushing", "None", "Nitrate interaction still matters.", "Tadalafil works longer than sildenafil."),
  d("dutasteride", "Avodart", "5-alpha-reductase inhibitor", "benign prostatic hyperplasia", "sexual dysfunction", "None", "Similar class idea to finasteride.", "Dutasteride shrinks the prostate."),
  d("levonorgestrel", "Plan B One-Step", "emergency contraceptive", "emergency contraception", "nausea, irregular bleeding", "None", "Used after unprotected intercourse, not as a daily contraceptive.", "Levonorgestrel emergency contraception is the morning-after pill."),
  d("norethindrone", "Micronor", "progestin-only contraceptive", "pregnancy prevention", "irregular bleeding", "None", "Progestin-only pill option.", "Norethindrone can be the mini-pill."),
  d("progesterone", "Prometrium", "progestin hormone", "hormone therapy support", "drowsiness", "None", "Shows up in hormone-therapy regimens.", "Progesterone balances estrogen therapy."),
  d("alendronate", "Fosamax", "bisphosphonate", "osteoporosis", "esophageal irritation", "None", "Take with plain water and stay upright.", "Bisphosphonates need upright dosing."),
  d("ibandronate", "Boniva", "bisphosphonate", "osteoporosis", "esophageal irritation", "None", "Another osteoporosis bisphosphonate.", "Boniva follows the bisphosphonate upright rule."),
  d("denosumab", "Prolia", "RANKL inhibitor", "osteoporosis", "muscle pain, infection risk", "None", "Injected osteoporosis treatment.", "Prolia strengthens bone by blocking resorption."),
  d("calcitriol", "Rocaltrol", "active vitamin D", "hypocalcemia, renal-related calcium management", "hypercalcemia", "None", "Stronger than routine OTC vitamin D.", "Calcitriol is activated vitamin D."),
  d("magnesium oxide", "Mag-Ox", "mineral supplement", "magnesium replacement, constipation off-label", "diarrhea", "None", "Can loosen stools.", "Magnesium oxide often causes diarrhea."),
  d("clotrimazole cream", "Lotrimin AF", "topical antifungal", "fungal skin infection", "mild irritation", "None", "Common athlete's-foot treatment.", "Clotrimazole fights fungal skin infections."),
  d("ketoconazole shampoo", "Nizoral", "topical antifungal", "seborrheic dermatitis, dandruff", "mild irritation", "None", "Often used on scalp conditions.", "Ketoconazole shampoo treats dandruff fungus."),
  d("baclofen", "Lioresal", "muscle relaxant", "spasticity", "drowsiness, weakness", "None", "Another sedating muscle relaxant.", "Baclofen relaxes tight muscles."),
  d("dexamethasone", "Decadron", "corticosteroid", "inflammation, cerebral edema", "hyperglycemia, insomnia", "None", "Potent steroid that appears in many inpatient settings.", "Dexamethasone is a strong steroid."),
  d("benztropine", "Cogentin", "anticholinergic", "drug-induced EPS, Parkinsonism", "dry mouth, constipation", "None", "Classic EPS management clue.", "Benztropine treats movement side effects."),
  d("tamoxifen", "Soltamox", "selective estrogen receptor modulator", "breast cancer therapy", "hot flashes, clot risk", "None", "Important endocrine oncology drug.", "Tamoxifen blocks estrogen effects in breast tissue."),
];

export const DRUG_CLASS_GUIDES = [
  {
    className: "ACE inhibitors",
    examples: ["lisinopril"],
    pattern: "-pril",
    focus: "Hypertension and heart failure",
    examPearl: "Watch for dry cough, hyperkalemia, and pregnancy warnings.",
  },
  {
    className: "ARBs",
    examples: ["losartan", "valsartan"],
    pattern: "-sartan",
    focus: "Hypertension and kidney protection",
    examPearl: "Used when cough limits ACE inhibitor use.",
  },
  {
    className: "Beta blockers",
    examples: ["metoprolol succinate", "carvedilol", "propranolol"],
    pattern: "-olol",
    focus: "Blood pressure, rate control, and some cardiac conditions",
    examPearl: "Bradycardia and fatigue are common clue words.",
  },
  {
    className: "Statins",
    examples: ["atorvastatin", "rosuvastatin", "simvastatin"],
    pattern: "-statin",
    focus: "Lowering LDL cholesterol",
    examPearl: "Muscle pain and liver enzyme monitoring are classic test points.",
  },
  {
    className: "PPIs",
    examples: ["omeprazole", "pantoprazole"],
    pattern: "-prazole",
    focus: "GERD and ulcer disease",
    examPearl: "Separate from H2 blockers like famotidine.",
  },
  {
    className: "SSRIs",
    examples: ["sertraline", "fluoxetine", "escitalopram"],
    pattern: "varies",
    focus: "Depression and anxiety",
    examPearl: "Nausea and sexual side effects appear often in counseling questions.",
  },
  {
    className: "Benzodiazepines",
    examples: ["alprazolam", "lorazepam", "diazepam"],
    pattern: "-pam / -lam",
    focus: "Anxiety, panic, insomnia, seizure support",
    examPearl: "Schedule IV, sedating, and dependence-prone.",
  },
  {
    className: "Opioids",
    examples: ["hydrocodone/acetaminophen", "morphine sulfate", "hydromorphone"],
    pattern: "varies",
    focus: "Pain management",
    examPearl: "Respiratory depression and constipation are high-yield adverse effects.",
  },
  {
    className: "Insulins",
    examples: ["insulin glargine", "insulin lispro", "insulin aspart"],
    pattern: "varies",
    focus: "Basal versus mealtime glucose control",
    examPearl: "Know rapid versus long acting and basic storage rules.",
  },
  {
    className: "Antibiotics",
    examples: ["amoxicillin", "azithromycin", "doxycycline", "nitrofurantoin"],
    pattern: "varies",
    focus: "Common outpatient infections",
    examPearl: "Questions often hinge on counseling warnings such as sun sensitivity or avoiding alcohol.",
  },
];

export const CONTROLLED_SUBSTANCE_QUICK_LOOKUP = [
  { name: "amphetamine/dextroamphetamine", schedule: "CII" },
  { name: "methylphenidate ER", schedule: "CII" },
  { name: "lisdexamfetamine", schedule: "CII" },
  { name: "hydrocodone/acetaminophen", schedule: "CII" },
  { name: "oxycodone/acetaminophen", schedule: "CII" },
  { name: "morphine sulfate", schedule: "CII" },
  { name: "hydromorphone", schedule: "CII" },
  { name: "alprazolam", schedule: "CIV" },
  { name: "lorazepam", schedule: "CIV" },
  { name: "clonazepam", schedule: "CIV" },
  { name: "diazepam", schedule: "CIV" },
  { name: "zolpidem", schedule: "CIV" },
  { name: "temazepam", schedule: "CIV" },
  { name: "tramadol", schedule: "CIV" },
  { name: "phentermine", schedule: "CIV" },
  { name: "pregabalin", schedule: "CV" },
  { name: "codeine/acetaminophen", schedule: "CIII" },
  { name: "buprenorphine/naloxone", schedule: "CIII" },
  { name: "testosterone gel", schedule: "CIII" },
];
