export const SIG_CODES = [
  { term: "PO", meaning: "by mouth", example: "Take 1 tablet PO daily." },
  { term: "PRN", meaning: "as needed", example: "Take 1 tablet every 6 hours PRN pain." },
  { term: "BID", meaning: "twice daily", example: "Instill 1 drop BID." },
  { term: "TID", meaning: "three times daily", example: "Take 1 capsule TID with meals." },
  { term: "QID", meaning: "four times daily", example: "Apply cream QID." },
  { term: "QAM", meaning: "every morning", example: "Take 1 tablet QAM." },
  { term: "QPM", meaning: "every evening", example: "Take 1 tablet QPM." },
  { term: "QHS", meaning: "every night at bedtime", example: "Take 1 tablet QHS." },
  { term: "Q4H", meaning: "every 4 hours", example: "Use 2 puffs Q4H PRN wheeze." },
  { term: "Q6H", meaning: "every 6 hours", example: "Take 1 tablet Q6H PRN pain." },
  { term: "Q8H", meaning: "every 8 hours", example: "Take 1 capsule Q8H." },
  { term: "Q12H", meaning: "every 12 hours", example: "Inject every Q12H as directed." },
  { term: "AC", meaning: "before meals", example: "Take 1 tablet AC." },
  { term: "PC", meaning: "after meals", example: "Take 1 tablet PC." },
  { term: "SL", meaning: "sublingual", example: "Place 1 tablet SL at onset of chest pain." },
  { term: "SQ", meaning: "subcutaneous", example: "Inject SQ once daily." },
  { term: "IM", meaning: "intramuscular", example: "Administer IM per protocol." },
  { term: "IV", meaning: "intravenous", example: "Infuse IV over 30 minutes." },
  { term: "OU", meaning: "both eyes", example: "Instill 1 drop OU nightly." },
  { term: "OD", meaning: "right eye", example: "Instill 1 drop OD daily." },
  { term: "OS", meaning: "left eye", example: "Instill 1 drop OS daily." },
  { term: "AU", meaning: "both ears", example: "Place 4 drops AU BID." },
  { term: "AD", meaning: "right ear", example: "Place 2 drops AD BID." },
  { term: "AS", meaning: "left ear", example: "Place 2 drops AS BID." },
  { term: "gtt", meaning: "drop", example: "1 gtt OU QID." },
  { term: "tab", meaning: "tablet", example: "Take 1 tab daily." },
  { term: "cap", meaning: "capsule", example: "Take 1 cap BID." },
  { term: "ung", meaning: "ointment", example: "Apply ung topically BID." },
  { term: "susp", meaning: "suspension", example: "Shake susp well before use." },
  { term: "stat", meaning: "immediately", example: "Fill stat for ED discharge." },
];
